import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget825 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.440216064453125,
      height: 81.58968353271484,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.00856 0.279674C12.0265 8.54612 21.2169 17.7915 29.4468 27.8821C37.6781 37.9623 44.9248 48.8277 51.0852 60.3254C54.5286 66.7751 57.6219 73.4105 60.3513 80.2018C60.9077 81.5833 58.6934 82.1847 58.1431 80.8186C53.3087 68.8454 47.3277 57.3811 40.2858 46.59C33.278 35.838 25.2574 25.8 16.3363 16.6171C11.2906 11.4257 5.96685 6.51929 0.389302 1.92011C-0.753935 0.977006 0.874757 -0.655652 2.00855 0.279685L2.00856 0.279674Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
