import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget837 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.72900390625,
      height: 20.028671264648438,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M12.1468 20.0287L0 17.5322L5.6937 3.86325C6.03443 2.53935 6.87957 1.4064 8.04374 0.712921C9.20791 0.0194388 10.5961 -0.177959 11.9037 0.164032C13.2113 0.506023 14.3317 1.35948 15.019 2.53719C15.7064 3.7149 15.9046 5.12072 15.5702 6.44628L12.1468 20.0287Z')
            ..color = Color.fromARGB(255, 1, 28, 64),
        ],
      ),
    );
  }
}
