import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget824 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 110.26046752929688,
      height: 87.40401458740234,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M102.047 84.4219C107.622 79.6501 111.008 72.112 110.12 64.7736C109.232 57.4353 103.732 50.6891 96.5981 49.1307C89.4642 47.5724 81.332 51.8861 79.1652 58.946C77.9727 45.3348 76.5986 31.1533 69.4554 19.5621C62.9874 9.06655 51.7848 1.55656 39.6437 0.213033C27.5025 -1.13049 14.7194 3.94385 7.14746 13.652C-0.424524 23.3602 -2.27849 37.4738 3.02473 48.6196C6.93143 56.8303 14.1289 62.9408 21.6701 67.912C45.7292 83.7719 75.5744 90.3865 103.973 86.1525')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
