import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget841 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 269.8757629394531,
      height: 0.8790283203125,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M269.443 0.879028L0.432587 0.879028C0.317741 0.878691 0.207721 0.832231 0.12663 0.749842C0.0455396 0.667453 0 0.555861 0 0.439514C0 0.323167 0.0455396 0.211576 0.12663 0.129187C0.207721 0.0467976 0.317741 0.000337176 0.432587 0L269.443 0C269.558 0.000337176 269.668 0.0467976 269.749 0.129187C269.83 0.211576 269.876 0.323167 269.876 0.439514C269.876 0.555861 269.83 0.667453 269.749 0.749842C269.668 0.832231 269.558 0.878691 269.443 0.879028L269.443 0.879028Z')
            ..color = Color.fromARGB(255, 63, 61, 86),
        ],
      ),
    );
  }
}
