import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget831 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.593231201171875,
      height: 17.455535888671875,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M6.5925 17.4555L2.12536 17.4555L0 0L6.59323 0.000371746L6.5925 17.4555Z')
            ..color = Color.fromARGB(255, 255, 184, 184),
        ],
      ),
    );
  }
}
