import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget838 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.896148681640625,
      height: 23.720794677734375,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0.830277 23.7208L0.10003 6.76233C-0.453725 3.57442 1.34765 0.560795 4.11804 0.0681992C6.88922 -0.422596 9.59511 1.78842 10.1514 4.99976L12.8961 20.8458L0.830277 23.7208Z')
            ..color = Color.fromARGB(255, 1, 28, 64),
        ],
      ),
    );
  }
}
