import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget823 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 44.0045166015625,
      height: 59.402740478515625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M42.5422 0.203626C35.2484 6.22215 28.5572 12.9534 22.5652 20.3001C13.1879 31.7581 5.59958 44.6047 0.0647747 58.3923C-0.340403 59.3981 1.27182 59.836 1.67247 58.8413C10.7284 36.4336 25.1853 16.6837 43.7211 1.39797C44.5534 0.711325 43.3676 -0.477354 42.5422 0.203626Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
