import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget835 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.898468017578125,
      height: 18.132537841796875,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M8.94922 18.1325C13.8918 18.1325 17.8985 14.0734 17.8985 9.06627C17.8985 4.05911 13.8918 0 8.94922 0C4.00669 0 0 4.05911 0 9.06627C0 14.0734 4.00669 18.1325 8.94922 18.1325Z')
            ..color = Color.fromARGB(255, 255, 184, 184),
        ],
      ),
    );
  }
}
