import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget845 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 0.728729248046875,
      height: 112.21626281738281,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath('M0.728729 0L0 0L0 112.216L0.728729 112.216L0.728729 0Z')
            ..color = Color.fromARGB(255, 204, 204, 204),
        ],
      ),
    );
  }
}
