import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget844 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 52.10459899902344,
      height: 0.7382583618164062,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath('M52.1046 0L0 0L0 0.738258L52.1046 0.738258L52.1046 0Z')
            ..color = Color.fromARGB(255, 204, 204, 204),
        ],
      ),
    );
  }
}
