import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget840 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.916183471679688,
      height: 21.18022918701172,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M16.6411 20.2513C14.9716 22.0529 11.8711 21.0857 11.6536 18.6244C11.6365 18.4333 11.6377 18.241 11.6573 18.0502C11.7696 16.9599 12.3913 15.9701 12.2424 14.8189C12.2087 14.5324 12.1033 14.2594 11.9363 14.0257C10.6059 12.2209 7.48286 14.833 6.22728 13.1991C5.45737 12.1973 6.3624 10.6199 5.77159 9.50021C4.99183 8.02236 2.68218 8.75139 1.23379 7.94205C-0.377716 7.04155 -0.281318 4.53672 0.779487 3.01315C2.07318 1.15509 4.34143 0.163622 6.58144 0.0207307C8.82144 -0.12216 11.046 0.49128 13.1372 1.31692C15.5133 2.25501 17.8695 3.55147 19.3317 5.66808C21.1099 8.2421 21.281 11.7026 20.3917 14.7125C19.8508 16.5434 18.0045 18.78 16.6411 20.2513Z')
            ..color = Color.fromARGB(255, 47, 46, 65),
        ],
      ),
    );
  }
}
