import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget830 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.039352416992188,
      height: 5.4952239990234375,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M5.42431 0L14.0394 0L14.0394 5.49522L0 5.49522C0 4.77358 0.14032 4.059 0.412916 3.39229C0.685513 2.72558 1.08506 2.11979 1.58875 1.60951C2.09244 1.09923 2.69041 0.694454 3.34852 0.418293C4.00663 0.142132 4.71198 -2.09827e-14 5.42431 0L5.42431 0Z')
            ..color = Color.fromARGB(255, 47, 46, 65),
        ],
      ),
    );
  }
}
