import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget828 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.659759521484375,
      height: 11.812240600585938,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.82988 11.8122C9.04963 11.8122 11.6598 9.16798 11.6598 5.90612C11.6598 2.64426 9.04963 0 5.82988 0C2.61013 0 0 2.64426 0 5.90612C0 9.16798 2.61013 11.8122 5.82988 11.8122Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
