import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget836 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.80096435546875,
      height: 50.524749755859375,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M26.9803 50.5247L0 50.5247L0.0324693 50.3121C0.080952 49.9941 4.84095 18.4046 1.33026 8.07002C0.977975 7.05443 1.00896 5.94271 1.41724 4.94887C1.82552 3.95502 2.58223 3.1493 3.54173 2.68678L3.54182 2.68678C8.55979 0.292829 18.1921 -2.655 26.3221 4.49892C27.5184 5.56897 28.4527 6.90631 29.0509 8.4052C29.6491 9.90409 29.8949 11.5234 29.7688 13.1351L26.9803 50.5247Z')
            ..color = Color.fromARGB(255, 1, 28, 64),
        ],
      ),
    );
  }
}
