import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget834 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.67340087890625,
      height: 51.38020324707031,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M5.75838 50.8391C5.26194 50.5508 4.83396 50.1557 4.50455 49.6816C4.17515 49.2076 3.95236 48.6661 3.85185 48.0954C3.75135 47.5247 3.77559 46.9386 3.92286 46.3784C4.07014 45.8182 4.33687 45.2975 4.70426 44.8531L0 0L8.5035 0.393566L10.4586 44.5124C11.1547 45.1872 11.5823 46.0972 11.6604 47.0701C11.7385 48.0429 11.4617 49.0109 10.8823 49.7908C10.303 50.5706 9.46135 51.1081 8.51698 51.3013C7.5726 51.4945 6.59107 51.3301 5.75838 50.8391L5.75838 50.8391Z')
            ..color = Color.fromARGB(255, 255, 184, 184),
        ],
      ),
    );
  }
}
