import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget842 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 52.10462951660156,
      height: 111.84721374511719,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M49.7362 111.847L2.36839 111.847C1.74457 111.851 1.14488 111.603 0.700881 111.159C0.256881 110.715 0.00482309 110.111 0 109.479L0 2.36814C0.00482309 1.73616 0.256881 1.13192 0.700881 0.687979C1.14488 0.244034 1.74457 -0.00336738 2.36839 3.46268e-05L49.7362 3.46268e-05C50.3601 -0.00336738 50.9598 0.244034 51.4038 0.687979C51.8478 1.13192 52.0998 1.73616 52.1046 2.36814L52.1046 109.479C52.0998 110.111 51.8478 110.715 51.4038 111.159C50.9598 111.603 50.3601 111.851 49.7362 111.847L49.7362 111.847Z')
            ..color = Color.fromARGB(255, 255, 255, 255),
        ],
      ),
    );
  }
}
