import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget826 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 132.99423217773438,
      height: 191.57972717285156,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M132.994 191.58L0 191.58L0 53.3396C0 23.928 23.6191 0 52.6511 0L80.3432 0C109.375 0 132.994 23.928 132.994 53.3396L132.994 191.58Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
