import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget839 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 31.729843139648438,
      height: 61.27598571777344,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M27.5361 0C31.8774 16.75 32.351 38.0463 31.1798 61.276L25.3499 60.5377L14.7832 16.2418L8.95334 61.276L2.39472 60.9069C0.435352 36.5331 -1.47242 15.6087 1.66598 1.84566L27.5361 0Z')
            ..color = Color.fromARGB(255, 47, 46, 65),
        ],
      ),
    );
  }
}
