import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget822 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.27702331542969,
      height: 63.621612548828125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.97963 61.4648C1.92118 57.9906 -0.543982 52.5024 0.102509 47.1595C0.749 41.8167 4.75315 36.905 9.94712 35.7705C15.1411 34.6359 21.0619 37.7766 22.6394 42.9166C23.5077 33.0068 24.5081 22.6817 29.7088 14.2425C34.418 6.60105 42.5742 1.13328 51.4138 0.155102C60.2534 -0.823073 69.5603 2.8714 75.0732 9.93959C80.5861 17.0078 81.9359 27.2835 78.0748 35.3983C75.2305 41.3763 69.9902 45.8251 64.4997 49.4445C46.7579 61.0415 25.479 65.7575 4.57803 62.7248L5.97963 61.4648Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
