import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget833 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.976516723632812,
      height: 50.018524169921875,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0.675551 48.2492C0.354185 47.7695 0.140542 47.2243 0.0496711 46.6519C-0.0411992 46.0796 -0.0070989 45.494 0.149592 44.9364C0.306283 44.3788 0.581742 43.8628 0.956567 43.4248C1.33139 42.9867 1.79647 42.6373 2.31903 42.401L17.5044 0L24.9765 4.1311L7.63813 44.651C7.97174 45.5667 7.9622 46.5745 7.61134 47.4835C7.26047 48.3926 6.59264 49.1396 5.73441 49.5831C4.87618 50.0266 3.88717 50.1358 2.95479 49.89C2.02241 49.6441 1.21144 49.0603 0.675551 48.2492L0.675551 48.2492Z')
            ..color = Color.fromARGB(255, 255, 184, 184),
        ],
      ),
    );
  }
}
