/* Component bars
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class BarsIconWidget extends StatelessWidget {
  const BarsIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 35.0,
      height: 35.0,
      child: Stack(
        children: [
          Positioned(
            top: 20.0,
            child: SvgWidget(
              painters: [
                SvgPathPainter.fill()
                  ..addPath(
                      'M0.78125 3.51562L21.0938 3.51562C21.5252 3.51562 21.875 3.16587 21.875 2.73438L21.875 0.78125C21.875 0.349756 21.5252 0 21.0938 0L0.78125 0C0.349756 0 0 0.349756 0 0.78125L0 2.73438C0 3.16587 0.349756 3.51562 0.78125 3.51562ZM0.78125 11.3281L21.0938 11.3281C21.5252 11.3281 21.875 10.9784 21.875 10.5469L21.875 8.59375C21.875 8.16226 21.5252 7.8125 21.0938 7.8125L0.78125 7.8125C0.349756 7.8125 0 8.16226 0 8.59375L0 10.5469C0 10.9784 0.349756 11.3281 0.78125 11.3281ZM0.78125 19.1406L21.0938 19.1406C21.5252 19.1406 21.875 18.7909 21.875 18.3594L21.875 16.4062C21.875 15.9748 21.5252 15.625 21.0938 15.625L0.78125 15.625C0.349756 15.625 0 15.9748 0 16.4062L0 18.3594C0 18.7909 0.349756 19.1406 0.78125 19.1406Z')
                  ..color = Theme.of(context).colorScheme.primary,
              ],
            ),
          ),
        ],
      ),
    );
  }
}
