import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Frame ban
    Autogenerated by FlutLab FTF Generator
  */
class BlockIconWidget extends StatelessWidget {
  const BlockIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      alignment: Alignment.center,
      children: [
        Positioned(
          width: 18.0,
          height: 20.0,
          child: SvgWidget(
            painters: [
              SvgPathPainter.fill()
                ..addPath(
                    'M9.6875 0C4.33727 0 0 4.33723 0 9.6875C0 15.0378 4.33727 19.375 9.6875 19.375C15.0377 19.375 19.375 15.0377 19.375 9.6875C19.375 4.33727 15.0378 0 9.6875 0ZM14.7698 4.60516C17.3264 7.16172 17.5042 11.0693 15.5775 13.8097L5.56523 3.7975C8.30758 1.86953 12.2147 2.05004 14.7698 4.60516ZM4.60516 14.7698C2.04859 12.2133 1.87078 8.30574 3.79746 5.56527L13.8098 15.5775C11.0675 17.5055 7.16031 17.325 4.60516 14.7698L4.60516 14.7698Z')
                ..color = Theme.of(context).backgroundColor,
            ],
          ),
        )
      ],
    );
  }
}
