import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Frame clipboard-list
    Autogenerated by FlutLab FTF Generator
  */
class ClipboardListIconWidget extends StatelessWidget {
  const ClipboardListIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 32.0,
      height: 32.0,
      child: Stack(
        fit: StackFit.expand,
        alignment: Alignment.center,
        children: [
          Positioned(
            left: 4.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 32.0,
            child: SvgWidget(
              painters: [
                SvgPathPainter.fill()
                  ..addPath(
                      'M21 4L16 4C16 1.79375 14.2063 0 12 0C9.79375 0 8 1.79375 8 4L3 4C1.34375 4 0 5.34375 0 7L0 29C0 30.6562 1.34375 32 3 32L21 32C22.6562 32 24 30.6562 24 29L24 7C24 5.34375 22.6562 4 21 4ZM6 26.5C5.16875 26.5 4.5 25.8312 4.5 25C4.5 24.1688 5.16875 23.5 6 23.5C6.83125 23.5 7.5 24.1688 7.5 25C7.5 25.8312 6.83125 26.5 6 26.5ZM6 20.5C5.16875 20.5 4.5 19.8312 4.5 19C4.5 18.1688 5.16875 17.5 6 17.5C6.83125 17.5 7.5 18.1688 7.5 19C7.5 19.8312 6.83125 20.5 6 20.5ZM6 14.5C5.16875 14.5 4.5 13.8313 4.5 13C4.5 12.1687 5.16875 11.5 6 11.5C6.83125 11.5 7.5 12.1687 7.5 13C7.5 13.8313 6.83125 14.5 6 14.5ZM12 2.5C12.8313 2.5 13.5 3.16875 13.5 4C13.5 4.83125 12.8313 5.5 12 5.5C11.1687 5.5 10.5 4.83125 10.5 4C10.5 3.16875 11.1687 2.5 12 2.5ZM20 25.5C20 25.775 19.775 26 19.5 26L10.5 26C10.225 26 10 25.775 10 25.5L10 24.5C10 24.225 10.225 24 10.5 24L19.5 24C19.775 24 20 24.225 20 24.5L20 25.5ZM20 19.5C20 19.775 19.775 20 19.5 20L10.5 20C10.225 20 10 19.775 10 19.5L10 18.5C10 18.225 10.225 18 10.5 18L19.5 18C19.775 18 20 18.225 20 18.5L20 19.5ZM20 13.5C20 13.775 19.775 14 19.5 14L10.5 14C10.225 14 10 13.775 10 13.5L10 12.5C10 12.225 10.225 12 10.5 12L19.5 12C19.775 12 20 12.225 20 12.5L20 13.5Z')
                  ..color = Theme.of(context).backgroundColor,
              ],
            ),
          )
        ],
      ),
    );
  }
}
