import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Frame door-closed
    Autogenerated by FlutLab FTF Generator
  */
class DoorClosedIconWidget extends StatelessWidget {
  const DoorClosedIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 32.0,
      height: 32.0,
      child: Stack(
        fit: StackFit.expand,
        alignment: Alignment.center,
        children: [
          Positioned(
            left: 0.0,
            top: 3.200000047683716,
            right: null,
            bottom: null,
            width: 32.0,
            height: 25.599998474121094,
            child: SvgWidget(
              painters: [
                SvgPathPainter.fill()
                  ..addPath(
                      'M31.2 22.4L25.6 22.4L25.6 2.54C25.6 1.139 24.5235 0 23.2 0L8.7995 0C7.476 0 6.3995 1.139 6.3995 2.54L6.3995 22.4L0.8 22.4C0.358 22.4 0 22.758 0 23.2L0 24.8C0 25.242 0.358 25.6 0.8 25.6L31.2 25.6C31.642 25.6 32 25.242 32 24.8L32 23.2C32 22.758 31.642 22.4 31.2 22.4ZM20.7995 14.4C19.916 14.4 19.1995 13.6835 19.1995 12.8C19.1995 11.9165 19.916 11.2 20.7995 11.2C21.683 11.2 22.3995 11.9165 22.3995 12.8C22.4 13.6835 21.6835 14.4 20.7995 14.4Z')
                  ..color = Theme.of(context).backgroundColor,
              ],
            ),
          )
        ],
      ),
    );
  }
}
