/* Frame long-arrow-alt-down
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class DownArrowIconWidget extends StatelessWidget {
  const DownArrowIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: SizedBox(
        width: 25.0,
        height: 25.0,
        child: Stack(
          // fit: StackFit.expand,
          // alignment: Alignment.center,
          children: [
            Positioned(
              left: 26.5,
              top: 5.5,
              child: SvgWidget(
                painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M7.32946 15.3292L7.32946 0.585938C7.32946 0.262354 7.06711 0 6.74353 0L4.00915 0C3.68557 0 3.42321 0.262354 3.42321 0.585938L3.42321 15.3292L1.17424 15.3292C0.130197 15.3292 -0.392655 16.5914 0.345578 17.3297L4.54768 21.5318C5.00534 21.9895 5.74734 21.9895 6.20495 21.5318L10.4071 17.3297C11.1453 16.5915 10.6224 15.3292 9.57839 15.3292L7.32946 15.3292L7.32946 15.3292Z')
                    ..color = Theme.of(context).backgroundColor,
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
