/* Frame window-minimize
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class MinimizeIconWidget extends StatelessWidget {
  const MinimizeIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 25.0,
      height: 25.0,
      child: Stack(
        fit: StackFit.expand,
        alignment: Alignment.center,
        children: [
          Positioned(
            left: 20.0,
            top: 12.5,
            child: SvgWidget(
              painters: [
                SvgPathPainter.fill()
                  ..addPath(
                      'M22.6562 0L2.34375 0C1.0498 0 0 1.0498 0 2.34375L0 3.90625C0 5.2002 1.0498 6.25 2.34375 6.25L22.6562 6.25C23.9502 6.25 25 5.2002 25 3.90625L25 2.34375C25 1.0498 23.9502 0 22.6562 0Z')
                  ..color = Theme.of(context).backgroundColor,
              ],
            ),
          )
        ],
      ),
    );
  }
}
