/* Frame moon
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class MoonIconWidget extends StatelessWidget {
  const MoonIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.90,
      child: SizedBox(
        width: 25.0,
        height: 25.0,
        child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Positioned(
              left: 1.3286621570587158,
              top: 9.324138683375338e-16,
              right: null,
              bottom: null,
              width: 22.34270477294922,
              height: 25.0,
              child: SvgWidget(
                painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M12.5 25C16.3556 25 19.8769 23.2458 22.2098 20.3715C22.5549 19.9463 22.1786 19.3251 21.6453 19.4267C15.5807 20.5816 10.0114 15.9317 10.0114 9.80977C10.0114 6.2833 11.8992 3.04048 14.9673 1.29443C15.4403 1.02529 15.3213 0.308252 14.7839 0.208984C14.0306 0.070065 13.2661 0.000114079 12.5 0C5.60015 -9.32414e-16 0 5.59136 0 12.5C0 19.3999 5.59136 25 12.5 25Z')
                    ..color = Theme.of(context).highlightColor,
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
