/* Frame sign-out-alt
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class SignoutIconWidget extends StatelessWidget {
  const SignoutIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.90,
      child: SizedBox(
        width: 25.0,
        height: 25.0,
        child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Positioned(
              left: 0.0,
              top: 3.1239616870880127,
              right: null,
              bottom: null,
              width: 24.608154296875,
              height: 18.753114700317383,
              child: SvgWidget(
                painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M24.2676 10.2061L16.0645 18.4092C15.332 19.1417 14.0625 18.629 14.0625 17.5792L14.0625 12.8917L7.42188 12.8917C6.77246 12.8917 6.25 12.3692 6.25 11.7198L6.25 7.03229C6.25 6.38287 6.77246 5.86041 7.42188 5.86041L14.0625 5.86041L14.0625 1.17291C14.0625 0.127992 15.3271 -0.389587 16.0645 0.342835L24.2676 8.54596C24.7217 9.00494 24.7217 9.74713 24.2676 10.2061ZM9.375 18.1651L9.375 16.212C9.375 15.8897 9.11133 15.626 8.78906 15.626L4.6875 15.626C3.82324 15.626 3.125 14.9278 3.125 14.0635L3.125 4.68854C3.125 3.82428 3.82324 3.12604 4.6875 3.12604L8.78906 3.12604C9.11133 3.12604 9.375 2.86237 9.375 2.5401L9.375 0.586976C9.375 0.26471 9.11133 0.0010385 8.78906 0.0010385L4.6875 0.0010385C2.09961 0.0010385 0 2.10065 0 4.68854L0 14.0635C0 16.6514 2.09961 18.751 4.6875 18.751L8.78906 18.751C9.11133 18.751 9.375 18.4874 9.375 18.1651Z')
                    ..color = Theme.of(context).highlightColor,
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
