/* Frame sort
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class SortIconWidget extends StatelessWidget {
  const SortIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: SizedBox(
        width: 15.0,
        height: 15.0,
        child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Positioned(
              left: 1.875,
              top: 1.875,
              child: SvgWidget(
                painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M0.705049 6.76904L7.6777 6.76904C8.30466 6.76904 8.61813 7.52783 8.17575 7.97021L4.68942 11.4565C4.41403 11.7319 3.96872 11.7319 3.69626 11.4565L0.207002 7.97021C-0.23538 7.52783 0.0780961 6.76904 0.705049 6.76904ZM8.17575 3.69287L4.68942 0.206543C4.41403 -0.0688477 3.96872 -0.0688477 3.69626 0.206543L0.207002 3.69287C-0.23538 4.13525 0.0780961 4.89404 0.705049 4.89404L7.6777 4.89404C8.30466 4.89404 8.61813 4.13525 8.17575 3.69287Z')
                    ..color = Theme.of(context).highlightColor,
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
