/* Frame user-plus
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

class UserPlusIconWidget extends StatelessWidget {
  const UserPlusIconWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.90,
      child: SizedBox(
        width: 25.0,
        height: 25.0,
        child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Positioned(
              left: 0.0,
              top: 2.5,
              right: null,
              bottom: null,
              width: 25.0,
              height: 20.0,
              child: SvgWidget(
                painters: [
                  SvgPathPainter.fill()
                    ..addPath(
                        'M24.375 8.125L21.875 8.125L21.875 5.625C21.875 5.28125 21.5938 5 21.25 5L20 5C19.6562 5 19.375 5.28125 19.375 5.625L19.375 8.125L16.875 8.125C16.5312 8.125 16.25 8.40625 16.25 8.75L16.25 10C16.25 10.3438 16.5312 10.625 16.875 10.625L19.375 10.625L19.375 13.125C19.375 13.4688 19.6562 13.75 20 13.75L21.25 13.75C21.5938 13.75 21.875 13.4688 21.875 13.125L21.875 10.625L24.375 10.625C24.7188 10.625 25 10.3438 25 10L25 8.75C25 8.40625 24.7188 8.125 24.375 8.125ZM8.75 10C11.5117 10 13.75 7.76172 13.75 5C13.75 2.23828 11.5117 0 8.75 0C5.98828 0 3.75 2.23828 3.75 5C3.75 7.76172 5.98828 10 8.75 10ZM12.25 11.25L11.5977 11.25C10.7305 11.6484 9.76562 11.875 8.75 11.875C7.73438 11.875 6.77344 11.6484 5.90234 11.25L5.25 11.25C2.35156 11.25 0 13.6016 0 16.5L0 18.125C0 19.1602 0.839844 20 1.875 20L15.625 20C16.6602 20 17.5 19.1602 17.5 18.125L17.5 16.5C17.5 13.6016 15.1484 11.25 12.25 11.25Z')
                    ..color = Theme.of(context).highlightColor,
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
