import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget507 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.0338134765625,
      height: 7.0054168701171875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.384158 5.28388C0.384158 5.28388 4.33384 -0.665843 8.03381 0.0616662C8.03381 0.0616662 4.80445 6.09543 0 7.00542L0.384158 5.28388Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
