import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget541 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.7083308696746826,
      height: 7.668867111206055,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M1.35417 7.66887C2.10206 7.66887 2.70833 5.95213 2.70833 3.83443C2.70833 1.71673 2.10206 0 1.35417 0C0.606286 0 0 1.71673 0 3.83443C0 5.95213 0.606286 7.66887 1.35417 7.66887Z')
            ..color = Color.fromARGB(255, 251, 190, 190),
        ],
      ),
    );
  }
}
