import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget500 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.166259765625,
      height: 6.90179443359375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.09725 3.97302e-07C1.09725 3.97302e-07 6.59556 -0.0168127 6.13937 6.86696C6.13937 6.86696 1.52224 7.69291 0 1.30136L1.09725 3.97302e-07Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
