import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget516 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 32.69476318359375,
      height: 51.35066223144531,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.225697 51.3507C0.297728 51.3195 7.65206 48.0349 15.2849 40.2027C19.7569 35.6155 23.4726 30.3478 26.2936 24.5961C29.8231 17.4098 31.9745 8.57885 32.6948 0L32.2602 0.204088C30.6395 19.4603 21.8733 32.6179 14.9032 39.7849C7.34474 47.5474 0.0720308 50.7984 0 50.8296L0.225697 51.3507Z')
          ..color = Color.fromARGB(255, 68, 64, 83),
      ]),
    );
  }
}
