import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget491 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.8861083984375,
      height: 7.926979064941406,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.88611 6.58001C6.88611 6.58001 4.67957 -0.178848 0 0.00362952C0 0.00362952 2.25456 7.14185 6.49474 7.92698L6.88611 6.58001Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
