import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget515 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.4466552734375,
      height: 27.5565185546875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 27.5229L0.417775 27.5565C0.506613 26.5145 0.573863 25.4484 0.619482 24.3848C1.01805 15.1456 1.63511 6.66043 2.44666 0.300128L2.20655 0C1.39261 6.37471 0.600276 15.1144 0.201707 24.368C0.156087 25.4244 0.0888378 26.4857 0 27.5229Z')
          ..color = Color.fromARGB(255, 68, 64, 83),
      ]),
    );
  }
}
