import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget503 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.071075439453125,
      height: 4.181953430175781,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.225682 2.07279C0.225682 2.07279 5.1454 -2.62601 9.07108 2.12562C9.07108 2.12562 4.04573 5.99366 0 3.11963L0.225682 2.07279Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
