import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget545 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.921005249023438,
      height: 9.921028137207031,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.96049 9.92103C7.7001 9.92103 9.92101 7.70013 9.92101 4.96051C9.92101 2.2209 7.7001 0 4.96049 0C2.22089 0 0 2.2209 0 4.96051C0 7.70013 2.22089 9.92103 4.96049 9.92103Z')
          ..color = Color.fromARGB(255, 251, 190, 190),
      ]),
    );
  }
}
