import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget496 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.8248291015625,
      height: 8.206695556640625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M3.82483 6.77088C3.82483 6.77088 2.00965 0.895581 0 0C0 0 0.396167 6.92695 3.36142 8.2067L3.82483 6.77088Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
