import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget505 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.302703857421875,
      height: 6.276336669921875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 4.85775C0 4.85775 3.8128 -1.14475 8.3027 0.195007C8.3027 0.195007 4.34582 6.55046 0.0432019 6.26714L0 4.85775Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
