import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget522 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.05000000074505806,
      child: Container(
        width: 188.72032165527344,
        height: 82.98411560058594,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath('M188.72 0L0 0L0 82.9841L188.72 82.9841L188.72 0Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
