import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget484 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.2528839111328125,
      height: 7.0493927001953125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.92533 0C1.92533 0 4.70088 0.890775 2.22546 7.04939C2.22546 7.04939 0.393499 6.64123 0.0645629 4.18978C-0.264373 1.73834 0.71043 0.89318 1.92533 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
