import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget509 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.959320068359375,
      height: 7.368736267089844,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 6.77568C0 6.77568 3.40223 0.0144061 5.95932 0C5.95932 0 4.21859 5.78166 0.112841 7.36874L0 6.77568Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
