import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget499 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.7079010009765625,
      height: 6.1469268798828125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.08763 0.0151467C1.08763 0.0151467 5.84646 -0.606703 5.7048 6.11852C5.7048 6.11852 1.40459 6.81961 0 1.25648L1.08763 0.0151467Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
