import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget514 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.129852294921875,
      height: 18.8408203125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 18.8048L0.276125 18.8408C1.70234 7.67847 3.78164 1.07325 6.12985 0.264107L6.03861 0C3.54874 0.864368 1.45503 7.36873 0 18.8048Z')
          ..color = Color.fromARGB(255, 68, 64, 83),
      ]),
    );
  }
}
