import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget495 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.20660400390625,
      height: 8.533233642578125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.2066 7.98099C4.2066 7.98099 2.48026 0.612261 0 0C0 0 0.33854 6.02897 3.95689 8.53323L4.2066 7.98099Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
