import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget527 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 76.83269500732422,
      height: 8.163467407226562,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M76.8327 0L0 0L0 8.16347L76.8327 8.16347L76.8327 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
