import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget488 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.923370361328125,
      height: 5.100944519042969,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.92337 4.14783C7.92337 4.14783 6.41793 -1.33371 0 0.306193C0 0.306193 2.14171 5.51401 7.49838 5.07463L7.92337 4.14783Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
