import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget512 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.604095458984375,
      height: 7.517597198486328,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.75397 5.29906C2.75397 5.29906 9.36399 0.737114 9.6041 0C9.6041 0 6.24266 6.38912 0 7.5176L2.75397 5.29906Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
