import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget485 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.3480224609375,
      height: 5.48065185546875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.34418 4.33058C6.34418 4.33058 6.72116 -0.454613 0.0101967 0.0351903C0.0101967 0.0351903 -0.470012 4.35698 5.16047 5.48065L6.34418 4.33058Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
