import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget498 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.823272705078125,
      height: 11.219966888427734,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.46187 7.98579C1.46187 7.98579 4.1678 0.422579 4.82327 0C4.82327 0 -0.482935 4.90769 0.0356822 11.22L1.46187 7.98579Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
