import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget486 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.6280364990234375,
      height: 5.4004669189453125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.62804 4.10871C7.62804 4.10871 6.70844 -1.31523 1.2705e-06 0.300665C1.2705e-06 0.300665 -0.024018 4.98989 6.53316 5.40047L7.62804 4.10871Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
