import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget501 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.6268310546875,
      height: 4.551727294921875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.441779 0.446104C0.441779 0.446104 5.43348 -1.89489 8.62683 4.14851C8.62683 4.14851 4.0169 6.09814 0 1.42333L0.441779 0.446104Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
