import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget543 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.52044677734375,
      height: 2.370452880859375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.61186 0.493494C1.246 0.885247 0.797303 1.1904 0.298509 1.38668L0.0776209 1.49233C0.0470583 1.50391 0.0209858 1.52494 0.00319044 1.55235C-0.00102887 1.57102 -0.00106334 1.59039 0.00308786 1.60907C0.00723906 1.62775 0.0154671 1.64527 0.0271946 1.66039C0.210981 1.94467 0.4826 2.16115 0.80072 2.27687C1.11884 2.39259 1.46605 2.40123 1.78954 2.30147C1.9325 2.26568 2.06495 2.19656 2.17609 2.09978C2.35912 1.88268 2.46396 1.61044 2.47381 1.32666C2.5465 1.03393 2.53401 0.726536 2.43781 0.440679C2.10407 -0.310841 1.98162 0.0300968 1.61186 0.493494Z')
          ..color = Color.fromARGB(255, 251, 190, 190),
      ]),
    );
  }
}
