import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget492 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.209014892578125,
      height: 8.8101806640625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.20901 7.54244C6.20901 7.54244 3.80801 -0.592234 0 0.0344333C0 0.0344333 1.66151 6.25309 6.07457 8.81018L6.20901 7.54244Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
