import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget487 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.187484741210938,
      height: 4.9729766845703125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.18748 3.9973C8.18748 3.9973 6.64603 -1.28495 0 0.294922C0 0.294922 1.58225 5.04654 7.74568 4.97211L8.18748 3.9973Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
