import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget520 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.800000011920929,
      child: Container(
        width: 1.920816421508789,
        height: 1.9208183288574219,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0.960408 1.92082C1.49083 1.92082 1.92082 1.49083 1.92082 0.960409C1.92082 0.42999 1.49083 0 0.960408 0C0.429989 0 0 0.42999 0 0.960409C0 1.49083 0.429989 1.92082 0.960408 1.92082Z')
            ..color = Color.fromARGB(255, 254, 210, 83),
        ]),
      ),
    );
  }
}
