import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget493 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.0025634765625,
      height: 8.811721801757812,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.00256 7.04938C6.00256 7.04938 3.7504 0.271315 0 0C0 0 1.53187 6.67002 5.92815 8.81172L6.00256 7.04938Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
