import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget497 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1.87579345703125,
      height: 12.175590515136719,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.51084 10.358L1.87579 0C1.87579 0 -1.88174 7.80813 1.23953 12.1756L1.51084 10.358Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
