import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget528 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.567047119140625,
      height: 8.163436889648438,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M16.567 0L0 0L0 8.16344L16.567 8.16344L16.567 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
