import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget518 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 234.8199462890625,
      height: 138.8991241455078,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0L0 134.755C3.41206e-15 135.854 0.436616 136.908 1.2138 137.685C1.99098 138.463 3.04506 138.899 4.14416 138.899L230.676 138.899C231.775 138.899 232.829 138.463 233.606 137.685C234.383 136.908 234.82 135.854 234.82 134.755L234.82 0L0 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
