import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget555 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 3.318115234375,
        height: 6.2042388916015625,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M3.31812 0L0.559413 6.20424C0.432162 5.3975 0.237693 4.59075 0.0432155 3.80322L0 3.89206L0 3.76241L1.50299 0.456199L3.31812 0Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
