import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget523 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 185.83917236328125,
      height: 81.154541015625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M185.839 0L0 0L0 81.1545L185.839 81.1545L185.839 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
