import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget481 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.8752899169921875,
      height: 2.0787200927734375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.87529 1.05943C5.87529 1.05943 2.92444 -0.887815 0 0.497583C0 0.497583 0.900391 2.23114 4.60276 2.06787L5.87529 1.05943Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
