import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget508 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.548736572265625,
      height: 7.8561553955078125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 6.72287C0 6.72287 3.06129 0.0456195 5.54874 0C5.54874 0 4.07932 6.62923 0.206484 7.85616L0 6.72287Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
