import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget504 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.020660400390625,
      height: 4.303314208984375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.177673 2.07027C0.177673 2.07027 5.1262 -2.73177 9.02066 2.29116C9.02066 2.29116 3.46708 6.23602 0 3.07868L0.177673 2.07027Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
