import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget517 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 234.8199462890625,
      height: 8.043420791625977,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M232.765 0L2.05527 0C1.51018 0 0.987414 0.216535 0.601976 0.601974C0.216537 0.987412 0 1.51018 0 2.05527L0 8.04342L234.82 8.04342L234.82 2.05527C234.82 1.51018 234.603 0.987412 234.218 0.601974C233.833 0.216535 233.31 0 232.765 0L232.765 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
