import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget494 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.282257080078125,
      height: 8.053031921386719,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.28226 6.93896C5.28226 6.93896 2.47546 0.153665 0 0C0 0 1.21972 6.68205 5.04215 8.05303L5.28226 6.93896Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
