import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget502 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.53558349609375,
      height: 4.3209381103515625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.422551 0.521448C0.422551 0.521448 5.53432 -1.96841 8.53558 3.93331C8.53558 3.93331 3.21015 5.76769 0 1.45545L0.422551 0.521448Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
