import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget483 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.7852935791015625,
      height: 3.3565673828125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.78529 2.13876C6.78529 2.13876 6.5668 -0.768896 2.17182e-05 0.19632C2.17182e-05 0.19632 -0.0311986 2.07153 2.27378 2.95991C4.57875 3.84829 5.63521 3.09917 6.78529 2.13876Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
