import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget489 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.140594482421875,
      height: 6.411506652832031,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.14059 5.43428C7.14059 5.43428 5.98331 -1.26942 0 0.21442C0 0.21442 1.73834 6.31306 6.70122 6.41151L7.14059 5.43428Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
