import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget511 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.51873779296875,
      height: 10.324394226074219,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.830743 8.66529L6.51874 0C6.51874 0 5.06134 8.54764 0 10.3244L0.830743 8.66529Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
