import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget510 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.65313720703125,
      height: 7.712089538574219,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 6.22826C0 6.22826 2.54506 0.63387 4.65314 0C4.65314 0 3.38062 6.81891 0.280927 7.71209L0 6.22826Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
