import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget513 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.709686279296875,
      height: 7.2895050048828125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.182479 7.28951C0.182479 7.28951 7.77207 -0.00719773 9.70969 5.32946e-06C9.70969 5.32946e-06 3.45026 0.285725 0 6.90053L0.182479 7.28951Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
