import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget490 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.4431610107421875,
      height: 6.129127502441406,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.44316 5.15686C7.44316 5.15686 6.05297 -1.59959 0 0.354834C0 0.354834 2.3722 6.74152 7.01337 6.08124L7.44316 5.15686Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
