import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget556 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 3.80322265625,
        height: 1.7690277099609375,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M3.80322 1.56328C3.64407 1.68235 3.45405 1.75318 3.25578 1.76735C2.95166 1.77815 2.64793 1.73674 2.3578 1.64491L0.196885 1.1047C0.129128 1.08802 0.0631791 1.06469 0 1.03506C0.0360153 0.658111 0.108043 0.221137 0.31213 0.0746783C0.617059 -0.129403 1.52945 0.144304 1.8752 0.192323C2.47065 0.273955 3.0757 0.369999 3.65675 0.482844C3.74683 0.836183 3.79598 1.19871 3.80322 1.56328L3.80322 1.56328Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
