import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget482 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.132781982421875,
      height: 5.74566650390625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.95604 0C1.95604 0 2.85401 3.41907 0.601856 5.74567C0.601856 5.74567 -0.75232 4.33626 0.601856 0.883578L1.95604 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
