import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget506 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.57525634765625,
      height: 7.671424865722656,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.0984504 6.39648C0.0984504 6.39648 3.9401 -1.16195 7.57526 0.153812C7.57526 0.153812 4.80446 5.9643 0 7.67142L0.0984504 6.39648Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
