import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget742 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.22149658203125,
      height: 9.2847900390625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.03164 1.03164L0 8.59703L7.2215 9.28479L6.18985 0L1.03164 1.03164Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
