import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget750 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 95.60061645507812,
      height: 31.63763427734375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M95.6006 0L0 0L0 31.6376L95.6006 31.6376L95.6006 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
