import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget807 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.75567626953125,
      height: 15.474967956542969,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 3.43888C0 3.43888 1.37557 10.3166 1.37557 11.3483C1.37557 12.38 7.22173 15.475 7.22173 15.475L13.7557 7.22165C13.7557 7.22165 9.62897 1.37555 9.62897 0L0 3.43888Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
