import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget746 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.0615386962890625,
      height: 120.92919921875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M3.06154 0L0 0L0 120.929L3.06154 120.929L3.06154 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
