import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget778 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.9987945556640625,
      height: 4.6599578857421875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M4.99879 0L0 0L0 4.65996L4.99879 4.65996L4.99879 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
