import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget803 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.234825134277344,
      height: 0.687652587890625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M40.2348 0L0 0L0 0.687653L40.2348 0.687653L40.2348 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
