import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget781 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.7510833740234375,
      height: 2.7511749267578125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M1.37554 2.75117C2.13523 2.75117 2.75108 2.1353 2.75108 1.37559C2.75108 0.615871 2.13523 0 1.37554 0C0.615851 0 0 0.615871 0 1.37559C0 2.1353 0.615851 2.75117 1.37554 2.75117Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
