import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget747 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 59.818634033203125,
      height: 153.1310272216797,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M59.8177 76.4277C60.0126 118.714 30.2622 153.131 30.2622 153.131C30.2622 153.131 0.195845 118.989 0.000953368 76.7034C-0.193938 34.4174 29.5564 0 29.5564 0C29.5564 0 59.6228 34.1417 59.8177 76.4277Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
