import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget739 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 297.8427734375,
      height: 119.19322967529297,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0.670983 119.193L0 119.042C7.48156 85.7707 26.2834 55.5573 52.9418 33.9673C73.0966 17.67 97.0675 6.77021 122.598 2.29435C148.128 -2.1815 174.377 -0.0861942 198.874 8.38299C223.37 16.8522 245.309 31.4166 262.623 50.7048C279.937 69.9931 292.057 93.3706 297.843 118.636L297.172 118.789C281.335 49.2515 220.391 0.685803 148.967 0.685803C78.4797 0.685803 16.112 50.5253 0.670983 119.193Z')
            ..color = Color.fromARGB(255, 63, 61, 86),
        ],
      ),
    );
  }
}
