import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget740 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.2218017578125,
      height: 9.2847900390625,
      child: SvgWidget(
        painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M6.19012 1.03164L7.2218 8.59703L0 9.28479L1.03169 0L6.19012 1.03164Z')
            ..color = Color.fromARGB(255, 160, 97, 106),
        ],
      ),
    );
  }
}
