import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget762 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 10.14459228515625,
      height: 9.45684814453125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M10.1446 0L0 0L0 9.45685L10.1446 9.45685L10.1446 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
