import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget779 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.998870849609375,
      height: 4.8293304443359375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M4.99887 0L0 0L0 4.82933L4.99887 4.82933L4.99887 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
