import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget812 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.8388671875,
      height: 16.162765502929688,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.4072 0L7.56548 0C7.56548 0 11.3482 0.687777 12.3799 7.56555C13.4115 14.4433 14.4432 16.1628 13.4115 16.1628C12.3799 16.1628 0 15.8189 0 15.475C0 15.1311 2.4072 0 2.4072 0Z')
          ..color = Color.fromARGB(255, 208, 205, 225),
      ]),
    );
  }
}
