import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget805 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 35.0765380859375,
      height: 35.07654571533203,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M35.0765 14.7872L20.2894 14.7872L20.2894 0L14.7872 0L14.7872 14.7872L0 14.7872L0 20.2894L14.7872 20.2894L14.7872 35.0765L20.2894 35.0765L20.2894 20.2894L35.0765 20.2894L35.0765 14.7872Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
