import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget806 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.881988525390625,
      height: 17.882131576538086,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.94099 17.8821C13.879 17.8821 17.882 13.8791 17.882 8.94107C17.882 4.00305 13.879 0 8.94099 0C4.00302 0 0 4.00305 0 8.94107C0 13.8791 4.00302 17.8821 8.94099 17.8821Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
