import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget804 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 55.70989990234375,
      height: 55.70977020263672,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M27.8549 55.7098C43.2388 55.7098 55.7099 43.2387 55.7099 27.8549C55.7099 12.4711 43.2388 0 27.8549 0C12.4711 0 0 12.4711 0 27.8549C0 43.2387 12.4711 55.7098 27.8549 55.7098Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
