import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget760 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 39.473899841308594,
      height: 101.04994201660156,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M39.4733 50.434C39.6019 78.3382 19.9698 101.05 19.9698 101.05C19.9698 101.05 0.129222 78.5201 0.000628984 50.6159C-0.127964 22.7118 19.5041 0 19.5041 0C19.5041 0 39.3447 22.5298 39.4733 50.434Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
