import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget759 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 2.020294189453125,
      height: 79.80017852783203,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M2.02029 0L0 0L0 79.8002L2.02029 79.8002L2.02029 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
