import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget749 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 251.03781127929688,
      height: 53.99034118652344,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 53.9903L25.7916 0L231.78 0L251.038 53.9903L0 53.9903Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
