import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget755 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 391.0,
      height: 0.6876373291015625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M391 0L0 0L0 0.687637L391 0.687637L391 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
