import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget767 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.9393310546875,
      height: 7.6701812744140625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M7.93933 0L0 0L0 7.67018L7.93933 7.67018L7.93933 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
