import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget787 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 75.65524291992188,
      height: 0.6876068115234375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M75.6552 0L0 0L0 0.687607L75.6552 0.687607L75.6552 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
