import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget810 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 44.802703857421875,
      height: 31.917064666748047,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M33.7982 0C33.7982 0 31.8068 5.12075 32.2228 10.1872C32.2989 11.0943 32.6043 11.9672 33.1104 12.7238L33.1104 12.7238L8.71335 24.3063C8.71335 24.3063 -2.31024 25.4477 0.440884 30.2621C3.192 35.0765 13.1648 27.8549 13.1648 27.8549C13.1648 27.8549 39.3005 24.0721 41.3638 20.2894C43.4271 16.5066 44.8027 0.687775 44.8027 0.687775L33.7982 0Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
