import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget748 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 236.93841552734375,
      height: 50.20770263671875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M236.938 0L0 0L0 50.2077L236.938 50.2077L236.938 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
