import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget754 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.805191040039062,
      height: 36.4521484375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M20.8052 0L0 0L0 36.4521L20.8052 36.4521L20.8052 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
