import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget751 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 113.48280334472656,
      height: 31.637630462646484,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M15.131 0L0 31.6376L113.483 31.6376L104.542 0L15.131 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
