import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget809 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 10.049041748046875,
      height: 15.818801879882812,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.20302 0L0.764186 2.40721C0.764186 2.40721 -0.955232 7.56551 0.764186 9.97272C2.4836 12.3799 3.17137 15.8188 3.17137 15.8188L10.049 15.131L4.20302 0Z')
          ..color = Color.fromARGB(255, 208, 205, 225),
      ]),
    );
  }
}
