import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget753 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.234825134277344,
      height: 38.859344482421875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M40.2348 0L0 0L0 38.8593L40.2348 38.8593L40.2348 0Z')
          ..color = Color.fromARGB(255, 204, 204, 204),
      ]),
    );
  }
}
