import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget795 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.234825134277344,
      height: 0.6876068115234375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M40.2348 0L0 0L0 0.687607L40.2348 0.687607L40.2348 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
