import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget741 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.092681884765625,
      height: 46.431434631347656,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.18335 0C7.18335 0 7.87112 9.28495 7.87112 9.62884C7.87112 9.97273 3.05675 33.7009 3.05675 33.7009C3.05675 33.7009 -3.82093 46.7687 3.05675 46.4248C9.93442 46.0809 7.87112 34.0448 7.87112 34.0448L15.0927 14.0994L11.9977 0L7.18335 0Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
