import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget770 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.9393463134765625,
      height: 7.4010467529296875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M7.93935 0L0 0L0 7.40105L7.93935 7.40105L7.93935 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
