import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget752 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 75.48330688476562,
      height: 40.234893798828125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M75.4833 0L0 0L0 40.2349L75.4833 40.2349L75.4833 0Z')
          ..color = Color.fromARGB(255, 204, 204, 204),
      ]),
    );
  }
}
