import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget744 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.27984619140625,
      height: 12.265945434570312,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M9.77083 1.71945C9.77083 1.71945 11.4902 0 9.08306 0C7.53765 0.0315185 6.01552 0.382787 4.61258 1.03167L2.89316 7.2217C2.89316 7.2217 -4.15645 12.8959 3.75287 12.2081C11.6622 11.5203 10.4586 12.0362 10.4586 12.0362C10.4586 12.0362 12.8658 11.3484 13.2097 10.6606C13.5535 9.97283 12.5219 0 12.5219 0C12.5219 0 11.4902 2.75112 9.77083 1.71945Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
