import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget745 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.280059814453125,
      height: 12.265945434570312,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.50917 1.71945C4.50917 1.71945 2.78974 0 5.19694 0C6.74236 0.0315185 8.2645 0.382787 9.66745 1.03167L11.3869 7.2217C11.3869 7.2217 18.4365 12.8959 10.5272 12.2081C2.6178 11.5203 2.78974 12.0362 2.78974 12.0362C2.78974 12.0362 0.382547 11.3484 0.0386617 10.6606C-0.305224 9.97283 1.75809 0 1.75809 0C1.75809 0 2.78974 2.75112 4.50917 1.71945Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
