import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget702 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 206.9332275390625,
        height: 52.00006103515625,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M206.933 22.9334C206.933 30.0026 160.61 52.0001 103.467 52.0001C46.3236 52.0001 0 30.0026 0 22.9334C0 15.8641 42.5902 0 99.7333 0C156.876 0 206.933 15.8641 206.933 22.9334Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
