import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget709 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.20000000298023224,
      child: Container(
        width: 7.5054168701171875,
        height: 2.7239837646484375,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M6.67357 2.48166C4.39617 2.50004 1.38193 2.12694 0.775166 1.75735C0.313086 1.47589 0.128959 0.465963 0.0673491 0C0.0246832 0.00183456 0 0.00262029 0 0.00262029C0 0.00262029 0.127765 1.62944 0.734525 1.99902C1.34129 2.36861 4.35553 2.74171 6.63293 2.72333C7.29032 2.71803 7.5174 2.48413 7.50493 2.13774C7.41361 2.34702 7.16287 2.47772 6.67357 2.48166Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
