import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget704 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.224197387695312,
      height: 18.34710693359375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0C0 10.1411 6.362 18.3471 14.2242 18.3471Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
