import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget722 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.452743530273438,
      height: 13.60797119140625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M5.0499 0.686506C5.0499 0.686506 2.89632 -1.62091 1.66571 2.22476C0.435092 6.07044 -0.487875 7.60872 0.281274 8.22402C1.05042 8.83933 1.6657 8.53167 1.35806 9.76228C1.05041 10.9929 2.28102 13.608 5.0499 13.608C7.81878 13.608 8.58792 11.6082 8.4341 10.2238C8.28027 8.83933 7.04966 7.14724 7.04966 7.14724L5.81904 2.84008L5.0499 0.686506Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
