import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget723 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.893157958984375,
      height: 8.147125244140625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.124 0L4.97107 2.76888C4.97107 2.76888 -2.41272 7.07604 0.817694 7.999C4.04811 8.92195 6.81702 5.23011 6.81702 5.23011L13.8932 3.38419L13.124 0Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
