import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget695 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0,
      height: 109.09077453613281,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M80 68.4478C80 98.5724 62.0914 109.091 40 109.091C17.9086 109.091 0 98.5724 0 68.4478C0 38.3232 40 0 40 0C40 0 80 38.3232 80 68.4478Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
