import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget706 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.0704345703125,
      height: 17.427871704101562,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0C0 9.63298 4.05689 17.4279 9.07043 17.4279Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
