import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget717 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 41.77980041503906,
      height: 63.316612243652344,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M16.5711 4.8289C16.5711 4.8289 38.876 0.82938 39.0299 0.0602419C39.1837 -0.708896 43.6447 5.90569 40.8758 18.8272C38.1069 31.7487 31.1847 62.2065 31.1847 62.2065C31.1847 62.2065 24.1086 64.3601 24.2624 62.668C24.4163 60.9759 26.7237 31.5949 26.7237 31.5949L25.1854 19.1348L22.5703 20.6731L11.6486 42.209L6.11078 60.8221C6.11078 60.8221 -0.965278 62.0527 0.111513 59.4376C1.18831 56.8226 4.72634 36.5173 4.72634 36.5173L14.4175 7.90544C14.4175 7.90544 14.1098 4.8289 16.5711 4.8289Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
