import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget703 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 206.9332275390625,
      height: 35.73338317871094,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M206.933 22.9334C206.933 30.0026 160.61 35.7334 103.467 35.7334C46.3236 35.7334 0 30.0026 0 22.9334C0 15.8641 42.5902 0 99.7333 0C156.876 0 206.933 15.8641 206.933 22.9334Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
