import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget705 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.873397827148438,
      height: 18.553314208984375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 18.5533C0 8.29826 7.09963 0 15.8734 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
