import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget719 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.08966827392578,
      height: 35.99571228027344,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.0724 0C13.0724 0 9.99579 2.92272 2.76584 2.15358C-4.46412 1.38444 4.76561 18.6132 4.76561 18.6132L7.68835 35.9957C7.68835 35.9957 20.61 34.4574 21.0715 31.5347C21.5329 28.612 13.0724 0 13.0724 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
