import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget718 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.921516418457031,
      height: 12.921600341796875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.46076 12.9216C10.0289 12.9216 12.9215 10.029 12.9215 6.4608C12.9215 2.8926 10.0289 0 6.46076 0C2.89258 0 0 2.8926 0 6.4608C0 10.029 2.89258 12.9216 6.46076 12.9216Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
