import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget710 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 70.40010070800781,
        height: 11.200057983398438,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M35.2001 11.2001C54.6405 11.2001 70.4001 8.69284 70.4001 5.60003C70.4001 2.50722 54.6405 0 35.2001 0C15.7596 0 0 2.50722 0 5.60003C0 8.69284 15.7596 11.2001 35.2001 11.2001Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
