import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget714 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.382820129394531,
      height: 10.506988525390625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.30712 1.12343C4.30712 1.12343 3.99947 3.89235 3.38416 3.89235C2.76886 3.89235 0.615307 4.96916 0.615307 4.96916L0 7.8919L4.30712 10.507L11.3831 9.73784L13.3828 6.66127L11.3831 4.6615C11.3831 4.6615 9.69101 0.969607 10.3063 0.200463C10.9216 -0.568681 4.30712 1.12343 4.30712 1.12343Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
