import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget707 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 18.347015380859375,
      height: 23.706863403320312,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 23.7069C0 10.6033 8.20599 0 18.347 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
