import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget699 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 87.46659088134766,
      height: 119.272705078125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M87.4666 74.8363C87.4666 107.773 67.8865 119.273 43.7333 119.273C19.5801 119.273 0 107.773 0 74.8363C0 41.9001 43.7333 0 43.7333 0C43.7333 0 87.4666 41.9001 87.4666 74.8363Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
