import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget734 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.068695068359375,
      height: 42.917945861816406,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M3.60781 0L2.53102 0.307658C2.53102 0.307658 -1.92987 35.9957 0.99279 42.9179C0.99279 42.9179 4.06928 41.2258 5.60752 41.5335L8.0687 12.4601L3.60781 0Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
