import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget694 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 224.27333068847656,
      height: 176.0079803466797,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M223.616 121.185C222.211 133.225 219.291 142.891 215.283 150.601C209.949 160.873 200.826 165.011 192.677 169.342C190.322 170.591 187.874 171.656 185.355 172.526C170.525 177.673 153.928 176.307 140.891 173.59C131.746 171.682 122.464 170.509 113.133 170.081C110.472 169.961 107.808 169.901 105.141 169.902C101.029 169.907 26.9893 171.313 8.96264 134.817C4.51198 125.814 1.46131 114.817 0.365313 101.411C-2.73602 63.5126 14.3093 38.6219 36.296 22.3526C77.8879 -8.42337 134.899 -7.1327 175.877 24.4539C203.173 45.4939 228.73 77.3366 223.616 121.185Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
