import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget700 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 36.665382385253906,
      height: 149.31175231933594,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M17.5774 114.234L18.0251 86.6696L36.6654 52.5683L18.0955 82.3456L18.2968 69.9515L31.1435 45.2795L18.3499 66.6715L18.712 44.38L32.4688 24.7379L18.7691 40.8747L18.9952 0L17.5734 54.1107L17.6902 51.8784L3.70374 30.4699L17.4659 56.1635L16.1627 81.0595L16.124 80.3984L0 57.8693L16.0752 82.7331L15.912 85.8464L15.883 85.8933L15.8963 86.1488L12.5899 149.312L17.0075 149.312L17.5374 116.687L33.5731 91.884L17.5774 114.234Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
