import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget726 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 72.53340148925781,
      height: 17.06652069091797,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M72.5334 0L0 0L0 17.0665L72.5334 17.0665L72.5334 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
