import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget721 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 18.916236877441406,
      height: 12.460006713867188,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.5152 3.3842C13.5152 3.3842 13.1718 2.30741 11.1899 3.3842C11.1899 3.3842 11.8231 0 9.66953 0C7.51593 0 6.74679 3.9995 6.74679 3.9995C6.74679 3.9995 6.13148 6.61456 1.97812 7.69135C-2.17524 8.76814 1.05515 12.46 3.97789 12.46C6.90062 12.46 10.7463 10.1526 10.7463 10.1526C10.7463 10.1526 18.7454 10.3064 18.8992 8.76816C19.053 7.22988 18.1301 2.61506 17.5148 2.61506C16.8995 2.61506 15.6688 4.76865 15.6688 4.76865L13.5152 3.3842Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
