import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget725 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.309921264648438,
      height: 19.178184509277344,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 12.7174C0 12.7174 1.69212 12.8713 2.46126 12.7174C3.2304 12.5636 4.30719 11.7945 4.30719 11.7945L10.1527 7.48732L5.07634 8.25645C5.07634 8.25645 5.99929 1.1804 5.69164 1.02657C5.38399 0.872741 20.613 -2.04997 20.3053 2.71867C19.9977 7.48732 11.3833 16.8708 6.46078 18.7167L3.2304 19.1782L0 12.7174Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
