import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget708 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.5060577392578125,
      height: 3.8114776611328125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 1.09C0 1.09 2.01722 1.02786 2.62516 0.594967C3.23309 0.162071 5.72814 -0.35484 5.87896 0.339436C6.02977 1.03371 8.91046 3.79246 6.63304 3.81083C4.35561 3.82919 1.34131 3.45609 0.734536 3.08649C0.127761 2.71689 0 1.09 0 1.09Z')
          ..color = Color.fromARGB(255, 168, 168, 168),
      ]),
    );
  }
}
