import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget716 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.12542724609375,
      height: 11.537109375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M3.30774 0C3.30774 0 1.92327 9.22969 0.231154 9.845C-1.46096 10.4603 6.69197 11.5371 6.69197 11.5371L7.30729 8.15289C7.30729 8.15289 7.46112 1.99976 8.07644 1.07679C8.69175 0.153825 3.30774 0 3.30774 0Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
