import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget713 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.690704345703125,
      height: 7.383613586425781,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.2294 0L13.6907 3.69194L1.53841 7.38361L0 0.615452L13.2294 0Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
