import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget727 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 53.86663818359375,
      height: 9.066696166992188,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M53.8666 0L0 0L0 9.0667L53.8666 9.0667L53.8666 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
