import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget711 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.466583251953125,
      height: 7.9999237060546875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M3.46658 0L0 0L0 7.99992L3.46658 7.99992L3.46658 0Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
