import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget696 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 33.535484313964844,
      height: 136.5655517578125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M16.0768 104.483L16.4864 79.2709L33.5355 48.0808L16.5507 75.316L16.7347 63.98L28.4848 41.4141L16.7835 60.98L17.1147 40.5914L29.6971 22.6261L17.1667 37.3853L17.3736 0L16.0731 49.4914L16.18 47.4498L3.38747 27.8688L15.9749 51.3691L14.7829 74.1397L14.7475 73.5352L0 52.929L14.7027 75.6704L14.5536 78.5181L14.5269 78.5608L14.5392 78.7946L11.5152 136.566L15.5555 136.566L16.0403 106.726L30.707 84.0402L16.0768 104.483Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
