import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget698 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 33.53514099121094,
      height: 136.5657196044922,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M16.0767 104.483L16.4862 79.271L33.5351 48.0808L16.5505 75.3161L16.7345 63.9801L28.4845 41.4142L16.7833 60.9801L17.1145 40.5915L29.6968 22.6262L17.1665 37.3854L17.3734 0L16.0729 49.4915L16.1798 47.4499L3.38743 27.8688L15.9748 51.3691L14.7828 74.1398L14.7473 73.5353L0 52.9291L14.7025 75.6705L14.5535 78.5182L14.5268 78.5609L14.5391 78.7947L11.5151 136.566L15.5553 136.566L16.0401 106.726L30.7066 84.0403L16.0767 104.483Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
