import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget712 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.333145141601562,
      height: 23.99997329711914,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M13.3331 0L0 0L0 24L13.3331 24L13.3331 0Z')
          ..color = Color.fromARGB(255, 255, 101, 132),
      ]),
    );
  }
}
