import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget733 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.713874816894531,
      height: 11.550079345703125,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.066536 0.922961C0.066536 0.922961 -0.702614 11.0756 2.98929 11.5371C6.68119 11.9986 3.29694 0 3.29694 0L0.066536 0.922961Z')
          ..color = Color.fromARGB(255, 255, 185, 185),
      ]),
    );
  }
}
