import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget254 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.541885375976562,
      height: 30.58929443359375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M19.5419 2.52047L17.0757 8.0894L16.5405 9.30082L7.40965 29.9275L7.11672 30.5893C4.64411 29.5583 2.26335 28.3195 0 26.8863L0.245964 26.192L7.69887 5.1639L9.52869 0L13.5354 1.00891L19.5419 2.52047Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
