import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget267 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 80.0897445678711,
      height: 5.0450286865234375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M77.5672 5.04503L2.52251 5.04503C1.8535 5.04503 1.21189 4.77926 0.738831 4.3062C0.265768 3.83313 0 3.19153 0 2.52251C0 1.8535 0.265768 1.21189 0.738831 0.738831C1.21189 0.265768 1.8535 2.05557e-14 2.52251 0L77.5672 0C78.2363 0 78.8779 0.265768 79.3509 0.738831C79.824 1.21189 80.0897 1.8535 80.0897 2.52251C80.0897 3.19153 79.824 3.83313 79.3509 4.3062C78.8779 4.77926 78.2363 5.04503 77.5672 5.04503Z')
          ..color = Color.fromARGB(255, 204, 204, 204),
      ]),
    );
  }
}
