import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget272 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.990478515625,
      height: 22.307296752929688,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M10.9953 0C25.6568 0.250385 25.6545 22.0591 10.9948 22.3073C-3.66618 22.0569 -3.66386 0.248262 10.9953 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
