import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';
import 'package:ead_app/helpers/transform/transform.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget251 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
      a: 0.39,
      b: 0.92,
      c: -0.92,
      d: 0.39,
      child: Container(
        width: 7.939194679260254,
        height: 10.585603713989258,
        child: SvgWidget(
          painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M3.96959 10.5856C6.16193 10.5856 7.93919 8.21594 7.93919 5.2928C7.93919 2.36967 6.16193 0 3.96959 0C1.77724 0 0 2.36967 0 5.2928C0 8.21594 1.77724 10.5856 3.96959 10.5856Z')
              ..color = Color.fromARGB(255, 47, 46, 65),
          ],
        ),
      ),
    );
  }
}
