import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget266 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 116.35086059570312,
      height: 5.0450286865234375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M113.828 5.04503L2.52251 5.04503C1.8535 5.04503 1.21189 4.77926 0.738831 4.3062C0.265768 3.83313 0 3.19153 0 2.52251C0 1.8535 0.265768 1.21189 0.738831 0.738831C1.21189 0.265768 1.8535 4.11113e-14 2.52251 2.05557e-14L113.828 2.05557e-14C114.497 0 115.139 0.265768 115.612 0.738831C116.085 1.21189 116.351 1.8535 116.351 2.52251C116.351 3.19153 116.085 3.83313 115.612 4.3062C115.139 4.77926 114.497 5.04503 113.828 5.04503Z')
          ..color = Color.fromARGB(255, 230, 230, 230),
      ]),
    );
  }
}
