import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';
import 'package:ead_app/helpers/transform/transform.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget255 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
      a: 0.48,
      b: 0.88,
      c: -0.88,
      d: 0.48,
      child: Container(
        width: 21.71108627319336,
        height: 21.71108627319336,
        child: SvgWidget(
          painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M10.8555 21.7111C16.8509 21.7111 21.7111 16.8509 21.7111 10.8555C21.7111 4.8602 16.8509 0 10.8555 0C4.86019 0 0 4.8602 0 10.8555C0 16.8509 4.86019 21.7111 10.8555 21.7111Z')
              ..color = Color.fromARGB(255, 160, 97, 106),
          ],
        ),
      ),
    );
  }
}
