import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget268 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 44.14699172973633,
      height: 5.045021057128906,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M41.6245 5.04502L2.52554 5.04502C2.19402 5.04542 1.86569 4.98046 1.55929 4.85387C1.2529 4.72728 0.974458 4.54154 0.739901 4.30726C0.505344 4.07298 0.319266 3.79477 0.192309 3.48853C0.0653514 3.18229 0 2.85403 0 2.52251C0 2.191 0.0653514 1.86273 0.192309 1.55649C0.319266 1.25025 0.505344 0.972037 0.739901 0.737761C0.974458 0.503485 1.2529 0.317741 1.55929 0.191151C1.86569 0.0645611 2.19402 -0.00039512 2.52554 1.80818e-06L41.6245 1.80818e-06C42.2935 1.80818e-06 42.9351 0.265769 43.4082 0.738831C43.8812 1.21189 44.147 1.8535 44.147 2.52251C44.147 3.19152 43.8812 3.83314 43.4082 4.3062C42.9351 4.77926 42.2935 5.04502 41.6245 5.04502Z')
          ..color = Color.fromARGB(255, 230, 230, 230),
      ]),
    );
  }
}
