import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget260 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 196.11166381835938,
      height: 0.7860174179077148,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M196.112 0L0 0L0 0.786017L196.112 0.786017L196.112 0Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
