import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget263 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.716106414794922,
      height: 4.716107368469238,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.35805 4.71611C3.66037 4.71611 4.71611 3.66037 4.71611 2.35805C4.71611 1.05574 3.66037 0 2.35805 0C1.05574 0 0 1.05574 0 2.35805C0 3.66037 1.05574 4.71611 2.35805 4.71611Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
