import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';
import 'package:ead_app/helpers/transform/transform.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget250 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
      a: 0.71,
      b: 0.71,
      c: -0.71,
      d: 0.71,
      child: Container(
        width: 10.585617065429688,
        height: 7.9392242431640625,
        child: SvgWidget(
          painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.29281 7.93922C8.21595 7.93922 10.5856 6.16197 10.5856 3.96961C10.5856 1.77726 8.21595 0 5.29281 0C2.36967 0 0 1.77726 0 3.96961C0 6.16197 2.36967 7.93922 5.29281 7.93922Z')
              ..color = Color.fromARGB(255, 47, 46, 65),
          ],
        ),
      ),
    );
  }
}
