import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget259 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.167282104492188,
      height: 10.558242797851562,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 5.8131C2.48065 7.52284 5.425 8.43277 8.43776 8.42073C7.36307 9.1659 6.13961 9.66924 4.85168 9.89607C8.85736 10.7553 12.9973 10.7786 17.0124 9.96441C17.9048 9.8213 18.766 9.52551 19.5581 9.09005C19.9528 8.86962 20.2967 8.56859 20.5674 8.20653C20.8381 7.84447 21.0296 7.42949 21.1294 6.98856C21.3962 5.46438 20.2086 4.07962 18.9743 3.14636C17.0846 1.73929 14.9057 0.769864 12.5954 0.308192C10.2851 -0.153479 7.90098 -0.0958457 5.61564 0.476929C4.12339 0.862656 2.6285 1.51438 1.65924 2.71277C0.689986 3.91116 0.402863 5.75867 1.32632 6.99271L0 5.8131Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
