import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget258 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.884002685546875,
      height: 18.612503051757812,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M29.7974 6.23792C29.7328 6.0128 29.6287 5.80098 29.4899 5.61232C28.9954 4.94934 28.4043 4.36425 27.7362 3.87656L27.7325 3.87294C25.4074 2.11186 20.7786 0.0542434 11.8503 6.62481e-07L11.8358 6.62481e-07C11.4265 -0.000321876 11.0258 0.117136 10.6814 0.338356C10.3371 0.559575 10.0637 0.875214 9.89384 1.24759L9.6733 1.73217L8.25208 4.85653C8.13154 5.12543 7.94036 5.35664 7.69888 5.52554C6.41503 6.4332 2.32881 9.72392 0.217007 16.0088C0.141067 16.233 0.0686895 16.4609 0 16.6959C9.02939 19.3337 18.6366 19.2469 27.6169 16.4464L27.8157 15.6255L29.7901 7.48191L29.8228 7.34809C29.9123 6.98225 29.9035 6.59926 29.7974 6.23792L29.7974 6.23792Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
