import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget252 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.169021606445312,
      height: 30.907516479492188,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M21.169 26.9044C18.9712 28.4313 16.6486 29.7704 14.226 30.9075L13.868 30.2747L10.4398 24.2574L10.1396 23.7294L8.38592 20.652L8.38221 20.6484L2.84581 10.9209L0 5.92693L8.4509 0L11.7381 6.95032L13.5208 10.7256L20.8581 26.2427L21.169 26.9044Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
