import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget249 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 25.581878662109375,
      height: 25.58190155029297,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M12.7909 25.5819C19.8552 25.5819 25.5819 19.8552 25.5819 12.791C25.5819 5.72671 19.8552 0 12.7909 0C5.72669 0 0 5.72671 0 12.791C0 19.8552 5.72669 25.5819 12.7909 25.5819Z')
          ..color = Color.fromARGB(255, 47, 46, 65),
      ]),
    );
  }
}
