import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget571 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 104.7905502319336,
        height: 57.59053039550781,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M104.791 0L104.791 57.5905L0 57.5905L0 0L52.3953 25.3244L104.791 0Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
