import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget578 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.480560302734375,
      height: 31.57635498046875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0C0 17.4533 10.9493 31.5764 24.4806 31.5764Z')
          ..color = Color.fromARGB(255, 70, 69, 91),
      ]),
    );
  }
}
