import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget601 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.009803771972656,
      height: 29.009883880615234,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M14.5049 0C11.6361 0 8.83173 0.850702 6.44642 2.44452C4.0611 4.03835 2.20197 6.30371 1.10413 8.95414C0.00628679 11.6046 -0.280961 14.521 0.278713 17.3347C0.838388 20.1484 2.21985 22.7329 4.24839 24.7615C6.27694 26.79 8.86147 28.1715 11.6751 28.7312C14.4888 29.2908 17.4053 29.0036 20.0557 27.9058C22.7061 26.8079 24.9715 24.9488 26.5653 22.5634C28.1591 20.1781 29.0098 17.3737 29.0098 14.5049C28.9986 10.6614 27.4668 6.9786 24.749 4.26083C22.0312 1.54306 18.3484 0.0112503 14.5049 0L14.5049 0ZM11.5272 22.2386L4.09345 14.8048L6.17854 12.7197L11.5342 18.0754L22.8383 6.7713L24.9233 8.85639L11.5272 22.2386L11.5272 22.2386Z')
          ..color = Color.fromARGB(255, 87, 184, 148),
      ]),
    );
  }
}
