import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget581 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 31.576364517211914,
      height: 40.80091857910156,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 40.8009C0 18.2488 14.123 0 31.5764 0Z')
          ..color = Color.fromARGB(255, 70, 69, 91),
      ]),
    );
  }
}
