import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget600 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.273521423339844,
      height: 24.317646026611328,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M12.1368 24.3176C18.8397 24.3176 24.2735 18.874 24.2735 12.1588C24.2735 5.44369 18.8397 0 12.1368 0C5.43381 0 0 5.44369 0 12.1588C0 18.874 5.43381 24.3176 12.1368 24.3176Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
