import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget576 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 87.02957153320312,
      height: 2.3682098388671875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M87.0296 0L0 0L0 2.36821L87.0296 2.36821L87.0296 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
