import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget579 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 27.318876266479492,
      height: 31.931167602539062,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 31.9312C0 14.2817 12.2188 0 27.3189 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
