import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget583 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.20000000298023224,
      child: Container(
        width: 12.917457580566406,
        height: 4.6884307861328125,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M11.4858 4.27137C7.5662 4.303 2.37841 3.66084 1.33413 3.02472C0.538848 2.54028 0.22194 0.801979 0.115903 0C0.04247 0.00315855 0 0.00451693 0 0.00451693C0 0.00451693 0.219892 2.80453 1.26418 3.44065C2.30847 4.07677 7.49627 4.71894 11.4158 4.68731C12.5473 4.67818 12.9381 4.27565 12.9166 3.67944C12.7594 4.03965 12.3279 4.26458 11.4858 4.27137Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
