import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget582 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.918350219726562,
      height: 6.5597381591796875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 1.87593C0 1.87593 3.47175 1.76901 4.51804 1.02397C5.56434 0.278925 9.85846 -0.610694 10.118 0.58419C10.3776 1.77907 15.3354 6.527 11.4158 6.55862C7.49624 6.59023 2.30846 5.94808 1.26418 5.31198C0.219894 4.67587 0 1.87593 0 1.87593Z')
          ..color = Color.fromARGB(255, 168, 168, 168),
      ]),
    );
  }
}
