import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget592 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.352447509765625,
      height: 15.35245132446289,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.67623 15.3525C11.9157 15.3525 15.3524 11.9157 15.3524 7.67623C15.3524 3.43676 11.9157 0 7.67623 0C3.43677 0 0 3.43676 0 7.67623C0 11.9157 3.43677 15.3525 7.67623 15.3525Z')
          ..color = Color.fromARGB(255, 160, 97, 106),
      ]),
    );
  }
}
