import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget569 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 140.90484619140625,
        height: 65.42021942138672,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0 0L140.905 0L140.905 56.9149C140.905 59.1707 140.009 61.334 138.414 62.9291C136.819 64.5241 134.655 65.4202 132.4 65.4202L8.50529 65.4202C6.24954 65.4202 4.08619 64.5241 2.49114 62.9291C0.896088 61.334 0 59.1707 0 56.9149L0 0L0 0Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
