import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget568 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 142.0889892578125,
      height: 131.1112060546875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M128.003 131.111L14.0855 131.111C10.3498 131.111 6.76709 129.627 4.12554 126.986C1.484 124.344 0 120.761 0 117.026L0 64.8341C2.01815e-07 64.0762 0.154402 63.3262 0.453776 62.63C0.753149 61.9337 1.19122 61.3057 1.74128 60.7843L62.1065 3.56302C64.5201 1.27521 67.719 -1.68267e-14 71.0445 0C74.37 -1.68267e-14 77.5689 1.27521 79.9824 3.56302L137.538 58.1204C138.975 59.4833 140.12 61.1248 140.903 62.9448C141.685 64.7648 142.089 66.7251 142.089 68.7062L142.089 117.026C142.089 118.875 141.725 120.707 141.017 122.416C140.309 124.125 139.271 125.678 137.963 126.986C136.655 128.294 135.103 129.331 133.394 130.039C131.685 130.747 129.853 131.111 128.003 131.111L128.003 131.111Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
