import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget573 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.30585479736328,
      height: 4.1442718505859375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M29.3059 0L0 0L0 4.14427L29.3059 4.14427L29.3059 0Z')
          ..color = Color.fromARGB(255, 242, 242, 242),
      ]),
    );
  }
}
