import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget580 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.610790252685547,
      height: 29.99420166015625,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0C0 16.5788 6.98217 29.9942 15.6108 29.9942Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
