import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget577 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 243.9195098876953,
      height: 0.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath('M0 0.5L243.919 0.5L243.919 -0.5L0 -0.5L0 0.5Z')
          ..color = Color.fromARGB(255, 63, 61, 86),
      ]),
    );
  }
}
