import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget570 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 104.7905502319336,
      height: 104.79063415527344,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M97.0405 0L7.75009 0C3.46983 0 0 3.46984 0 7.7501L0 97.0405C0 101.321 3.46983 104.791 7.75009 104.791L97.0405 104.791C101.321 104.791 104.791 101.321 104.791 97.0405L104.791 7.7501C104.791 3.46984 101.321 0 97.0405 0Z')
          ..color = Color.fromARGB(255, 1, 28, 64),
      ]),
    );
  }
}
