import 'package:flutter/material.dart';
import 'package:ead_app/helpers/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget587 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.10000000149011612,
      child: Container(
        width: 12.36724853515625,
        height: 28.5433349609375,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M12.3672 12.3331C12.1114 13.749 11.8116 15.1575 11.4558 16.5538C10.4665 20.4309 9.03114 24.2203 8.56812 28.1948C8.55349 28.3094 8.54132 28.4263 8.52914 28.5433C5.50251 24.2203 2.95351 19.5707 0 15.2013C0.22175 14.5775 0.44595 13.9536 0.614098 13.3127C0.856405 12.2772 1.02577 11.226 1.12096 10.1667C1.5133 6.83305 1.98607 3.50668 2.40034 0.175454L2.42228 0C2.59563 0.707211 2.84311 1.39417 3.16065 2.04943C5.14428 6.08007 9.85724 8.11729 12.1625 11.9749C12.2332 12.0943 12.3014 12.2137 12.3672 12.3331Z')
            ..color = Color.fromARGB(255, 0, 0, 0),
        ]),
      ),
    );
  }
}
